modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/LXGaming/NorthernCompass/issues"

[[mods]]
modId="northerncompass"
version="${version}"
displayName="NorthernCompass"
displayURL="https://lxgaming.github.io/"
logoFile="lxgaming.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="NorthernCompass\nSource - https://github.com/LXGaming/NorthernCompass"